services:
  mysql:
    container_name: mysql8_typeorm_reproducer
    image: mysql:8
    ports:
      - 3317:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "typeorm_reproducer"
    volumes:
      - typeorm_reproducer:/var/lib/mysql

volumes:
  typeorm_reproducer:
    external: true # Might need to change
